# Generated by Django 4.1.3 on 2022-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100, null=True)),
                ('password', models.IntegerField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(max_length=255, null=True)),
            ],
        ),
    ]
